version: "3"
services:
    notifyd:
        image: noyuno/notifyd
        restart: always
        ports:
            - "5050:5050"
        volumes:
            - ./data/notifyd:/data/notifyd
            - ./logs/notifyd:/logs/notifyd
        environment:
            DEPLOY: /data/notifyd
            DISCORD_TOKEN: ${DISCORD_TOKEN}
            NOTIFYD_TOKEN: "abc"
            DISCORD_CHANNEL_NAME: m1
            PORT: 5050
