#!/bin/bash -e

ln -sfnv ~/tv/EPGStation/config.json ~/EPGStation/config/config.json
ln -sfnv ~/tv/EPGStation/enc.sh ~/EPGStation/config/enc.sh
ln -sfnv ~/tv/EPGStation/enc.js ~/EPGStation/config/enc.js
