readOnlyOnce: false
port: 80
mirakurunPath: http+unix://%2Fvar%2Frun%2Fmirakurun.sock/
dbtype: mysql
mysql:
  host: localhost
  port: 3306
  user: noyuno
  password: 
  database: epgstation
ffmpeg: '/usr/bin/ffmpeg'
ffprobe: '/usr/bin/ffprobe'
recorded:
  - name: recorded
    path: '/mnt/hddts0-plain0/tv'
recordedFormat: '%YEAR%%MONTH%%DAY%-%HOUR%%MIN%-%CHNAME%-%TITLE%'
thumbnail: '/mnt/hddts0-plain0/tv/thumbs'
thumbnailSize: '960x540'
thumbnailPosition: 8
uploadTempDir: '/mnt/hddts0-plain0/tv/tmp'
encodeProcessNum: 4
concurrentEncodeNum: 1
encode:
  - name: 'H.264 1080p CPU'
    cmd: '/bin/bash %ROOT%/config/enc.sh'
    suffix: '.mp4'
    rate: 3.0
  - name: 'H.264 720p CPU'
    cmd: '/bin/bash %ROOT%/config/enc.sh 720p'
    suffix: '.mp4'
    rate: 3.0
streamFilePath: '/mnt/hddts0-plain0/tv/tmp'
stream:
  live:
    ts:
      m2ts:
        - name: '無変換'
      m2tsll: []
      hls:
        - name: '1080p encode'
          cmd: '%FFMPEG% -dual_mono_mode main -ss 0 -i pipe:0 -sn -threads 0 -ignore_unknown
                      -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                      -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a
                      copy -c:v libx264 -vf scale=-2:1080 -preset ultrafast -flags
                      +loop-global_header pipe:1'
        - name: '720p encode'
          cmd: '%FFMPEG% -dual_mono_mode main -ss 0 -i pipe:0 -sn -threads 0 -ignore_unknown
                      -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                      -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a
                      copy -c:v libx264 -vf scale=-2:720 -preset ultrafast -flags
                      +loop-global_header %OUTPUT%'
  recorded:
    ts:
      m2ts:
      m2tsll: []
      hls:
        - name: '1080p'
          cmd: '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0 -ignore_unknown
                      -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                      -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a
                      copy -c:v libx264 -vf scale=-2:1080 -preset ultrafast -flags
                      +loop-global_header %OUTPUT%'
        - name: '720p'
          cmd: '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0 -ignore_unknown
                      -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                      -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a
                      copy -c:v libx264 -vf scale=-2:720 -preset ultrafast -flags
                      +loop-global_header %OUTPUT%'
    encoded:
      hls:
        - name: 'copy'
          cmd: '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0 -ignore_unknown
                      -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                      -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a
                      copy -c:v copy -flags
                      +loop-global_header %OUTPUT%'
recordingPrepRecFailedCommand: '/home/noyuno/tv/EPGStation/notify.sh :x:録画準備が失敗しました'
# recordingStartCommand: '/home/noyuno/tv/EPGStation/notify.sh :record_button:録画を開始しました'
#recordingFinishCommand: '/home/noyuno/tv/EPGStation/notify.sh :white_circle:録画を終了しました'
recordingFailedCommand: '/home/noyuno/tv/EPGStation/notify.sh :x:録画が失敗しました'

