appenders:
  system:
    type: file
    maxLogSize: 1048576
    backups: 3
    filename: "%OperatorSystem%"
    pattern: "-yyyyMMdd"
  access:
    type: file
    maxLogSize: 1048576
    backups: 3
    filename: "%OperatorAccess%"
    pattern: "-yyyyMMdd"
  stream:
    type: file
    maxLogSize: 1048576
    backups: 3
    filename: "%OperatorStream%"
    pattern: "-yyyyMMdd"
  console:
    type: console
  stdout:
    type: stdout
  encode:
    type: file
    maxLogSize: 1048576
    backups: 3
    filename: "%ServiceEncode%"
    pattern: "-yyyyMMdd"
categories:
  default:
    appenders:
    - console
    - stdout
    level: info
  system:
    appenders:
    - system
    - stdout
    level: info
  access:
    appenders:
    - access
    - stdout
    level: info
  stream:
    appenders:
    - stream
    - stdout
    level: info
  encode:
    appenders:
    - stdout
    level: debug
