appenders:
  system:
    type: file
    maxLogSize: 1048576
    backups: 3
    filename: "%ServiceSystem%"
    pattern: "-yyyyMMdd"
  access:
    type: file
    maxLogSize: 1048576
    backups: 3
    filename: "%ServiceAccess%"
    pattern: "-yyyyMMdd"
  stream:
    type: file
    maxLogSize: 1048576
    backups: 3
    filename: "%ServiceStream%"
    pattern: "-yyyyMMdd"
  console:
    type: console
  stdout:
    type: stdout
categories:
  default:
    appenders:
    - console
    - stdout
    level: info
  system:
    appenders:
    - system
    - stdout
    level: info
  access:
    appenders:
    - access
    level: info
  stream:
    appenders:
    - stream
    - stdout
    level: info
  encode:
    appenders:
    - stdout
    level: debug
